import { StyleSheet } from 'react-native';

export const dashboardStyles = StyleSheet.create({
  screen: { backgroundColor: '#F1EDE3', flex: 1 },
  content: { paddingBottom: 140, paddingHorizontal: 20, paddingTop: 18 },
  header: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: 18 },
  greeting: { color: '#1F2E23', fontSize: 27, fontWeight: '800', letterSpacing: -0.7 },
  greetingSubtext: { color: '#718276', fontSize: 13, marginTop: 4 },
  profileButton: { backgroundColor: '#FAF8F3', borderColor: '#FFFFFF', borderRadius: 25, borderWidth: 2, elevation: 3, height: 50, overflow: 'hidden', shadowColor: '#B8AE9E', shadowOffset: { height: 3, width: 2 }, shadowOpacity: 0.24, shadowRadius: 5, width: 50 },
  profileImage: { height: '100%', width: '100%' },
  overviewGrid: { flexDirection: 'row', gap: 12, marginBottom: 14 },
  clayCard: { backgroundColor: '#F9F7F1', borderColor: '#FFFFFF', borderRadius: 22, borderWidth: 1, elevation: 2, shadowColor: '#B8AE9E', shadowOffset: { height: 5, width: 3 }, shadowOpacity: 0.2, shadowRadius: 9 },
  progressCard: { flex: 1, minHeight: 136, padding: 16 },
  focusCard: { minHeight: 136, padding: 16, width: 126 },
  cardEyebrowRow: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  cardEyebrow: { color: '#819286', fontSize: 10, fontWeight: '800', letterSpacing: 1 },
  progressValue: { color: '#25382B', fontSize: 36, fontWeight: '800', letterSpacing: -1, marginTop: 12 },
  progressTotal: { color: '#A7B1A8', fontSize: 18, fontWeight: '700' },
  progressLabel: { color: '#718276', fontSize: 12, marginTop: -3 },
  progressTrack: { backgroundColor: '#E6E1D6', borderRadius: 4, height: 7, marginTop: 14, overflow: 'hidden' },
  progressFill: { backgroundColor: '#6C927A', borderRadius: 4, height: '100%' },
  focusIcon: { alignItems: 'center', backgroundColor: '#F4E7D7', borderRadius: 17, height: 34, justifyContent: 'center', marginTop: 12, width: 34 },
  focusTitle: { color: '#25382B', fontSize: 13, fontWeight: '700', marginTop: 8 },
  focusMeta: { color: '#A87948', fontSize: 11, fontWeight: '700', marginTop: 3 },
  section: { marginBottom: 14 },
  packCard: { paddingBottom: 16, paddingHorizontal: 16, paddingTop: 16 },
  sectionTitle: { color: '#1F2E23', fontSize: 17, fontWeight: '700' },
  sectionSubtitle: { color: '#8A988E', fontSize: 11, marginTop: 3 },
  petRow: { alignItems: 'flex-start', gap: 16, paddingRight: 4 },
  petItem: { alignItems: 'center', width: 68 },
  petAvatarRing: { alignItems: 'center', borderColor: '#48956A', borderRadius: 35, borderWidth: 3, height: 68, justifyContent: 'center', width: 68 },
  selectedPetRing: { borderColor: '#E5A84B', borderWidth: 4 },
  petAvatar: { borderColor: '#F7F4EC', borderRadius: 29, borderWidth: 3, height: 58, width: 58 },
  selectedDot: { backgroundColor: '#3B8259', borderColor: '#F7F4EC', borderRadius: 5, borderWidth: 2, bottom: -3, height: 10, position: 'absolute', width: 10 },
  petName: { color: '#1F2E23', fontSize: 13, fontWeight: '700', marginTop: 9 },
  petAge: { color: '#718276', fontSize: 11, marginTop: 3 },
  addPetItem: { alignItems: 'center', width: 68 },
  addPetCircle: { alignItems: 'center', backgroundColor: '#FAF8F3', borderColor: '#D5CEBF', borderRadius: 35, borderStyle: 'dashed', borderWidth: 2, height: 68, justifyContent: 'center', width: 68 },
  addPetInner: { alignItems: 'center', backgroundColor: '#E8E2D4', borderRadius: 18, height: 34, justifyContent: 'center', width: 34 },
  addPetText: { color: '#1F2E23', fontSize: 13, fontWeight: '600', marginTop: 9 },
  routineSection: { padding: 16 },
  routineHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: 14 },
  viewAllButton: { backgroundColor: '#F1E9D9', borderRadius: 14, paddingHorizontal: 10, paddingVertical: 7 },
  viewAll: { color: '#C88A3C', fontSize: 11, fontWeight: '700', letterSpacing: 1 },
  routineCard: { alignItems: 'center', backgroundColor: '#F5F2EA', borderColor: '#FFFFFF', borderRadius: 18, borderWidth: 1, flexDirection: 'row', marginBottom: 8, minHeight: 70, padding: 12, shadowColor: '#C9C0B2', shadowOffset: { height: 2, width: 1 }, shadowOpacity: 0.14, shadowRadius: 4 },
  completedCard: { opacity: 0.82 },
  checkbox: { alignItems: 'center', borderColor: '#D5CEBF', borderRadius: 13, borderWidth: 2, height: 26, justifyContent: 'center', marginRight: 13, width: 26 },
  checkedBox: { backgroundColor: '#627C6B', borderColor: '#627C6B' },
  routineBody: { flex: 1 },
  routineTitle: { color: '#1F2E23', fontSize: 14, fontWeight: '700' },
  completedTitle: { color: '#819286', textDecorationLine: 'line-through' },
  routineMeta: { alignItems: 'center', flexDirection: 'row', marginTop: 5 },
  routineDetail: { color: '#718276', flexShrink: 1, fontSize: 11 },
  routineAvatar: { borderColor: '#EDE8DE', borderRadius: 18, borderWidth: 1, height: 36, marginLeft: 8, width: 36 },
  actions: { alignItems: 'center', flexDirection: 'row', gap: 10, marginTop: 8 },
  addRoutineButton: { alignItems: 'center', backgroundColor: '#557A63', borderRadius: 22, elevation: 2, flex: 1, flexDirection: 'row', height: 46, justifyContent: 'center', paddingHorizontal: 10, shadowColor: '#557A63', shadowOpacity: 0.2, shadowRadius: 5 },
  addRoutineText: { color: '#FFFFFF', fontSize: 13, fontWeight: '700', marginLeft: 7 },
  resetButton: { alignItems: 'center', backgroundColor: '#EAE5DA', borderColor: '#FFFFFF', borderRadius: 22, borderWidth: 1, height: 46, justifyContent: 'center', width: 46 },
  modalBackdrop: { alignItems: 'center', backgroundColor: '#202E2459', flex: 1, justifyContent: 'flex-end' },
  modal: { backgroundColor: '#FAF8F3', borderColor: '#EDE8DE', borderRadius: 30, borderWidth: 1, padding: 24, width: '100%' },
  modalHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: 18 },
  modalTitle: { color: '#1F2E23', fontSize: 18, fontWeight: '800' },
  modalSubtitle: { color: '#718276', fontSize: 12, marginTop: 3 },
  closeButton: { alignItems: 'center', backgroundColor: '#EAE5DA', borderRadius: 18, height: 36, justifyContent: 'center', width: 36 },
  formLabel: { color: '#44574A', fontSize: 11, fontWeight: '700', letterSpacing: 0.7, marginBottom: 7, textTransform: 'uppercase' },
  typeRow: { flexDirection: 'row', gap: 7, marginBottom: 16 },
  typeButton: { alignItems: 'center', backgroundColor: '#EAE5DA', borderRadius: 12, flex: 1, paddingVertical: 9 },
  activeTypeButton: { backgroundColor: '#627C6B' },
  typeText: { color: '#495B50', fontSize: 10, fontWeight: '600', marginTop: 4 },
  activeTypeText: { color: '#FFFFFF' },
  formInput: { backgroundColor: '#FFFFFF', borderColor: '#DDD6C8', borderRadius: 12, borderWidth: 1, color: '#1F2E23', fontSize: 14, marginBottom: 15, paddingHorizontal: 13, paddingVertical: 11 },
  modalActions: { flexDirection: 'row', gap: 10, marginTop: 4 },
  modalCancel: { alignItems: 'center', backgroundColor: '#EAE5DA', borderRadius: 22, flex: 1, paddingVertical: 13 },
  modalSave: { alignItems: 'center', backgroundColor: '#627C6B', borderRadius: 22, flex: 1, paddingVertical: 13 },
  modalCancelText: { color: '#4F6255', fontSize: 12, fontWeight: '700' },
  modalSaveText: { color: '#FFFFFF', fontSize: 12, fontWeight: '700' },
});
