import { StyleSheet } from 'react-native';

export const addPetStyles = StyleSheet.create({
  screen: { backgroundColor: '#F7F4EC', flex: 1 },
  scrollContent: { paddingBottom: 22, paddingHorizontal: 24, paddingTop: 12 },
  backButton: { alignItems: 'center', backgroundColor: '#EAE5DA', borderRadius: 22, height: 44, justifyContent: 'center', width: 44 },
  backArrow: { color: '#2C3B30', fontSize: 34, fontWeight: '300', lineHeight: 34, marginTop: -4 },
  heading: { marginBottom: 20, marginTop: 18 },
  title: { color: '#1F2E23', fontSize: 30, fontWeight: '800', letterSpacing: -0.5, lineHeight: 35 },
  subtitle: { color: '#718276', fontSize: 14, lineHeight: 20, marginTop: 6 },
  photoCard: { alignItems: 'center', backgroundColor: '#FAF8F3', borderColor: '#EDE8DE', borderRadius: 28, borderWidth: 1, flexDirection: 'row', justifyContent: 'space-between', padding: 16, shadowColor: '#28372D', shadowOpacity: 0.04, shadowRadius: 10 },
  addPhotoButton: { alignItems: 'center', backgroundColor: '#E4ECE7', borderRadius: 44, height: 88, justifyContent: 'center', width: 88 },
  cameraGlyph: { color: '#557A63', fontSize: 28, lineHeight: 30 },
  addPhotoText: { color: '#557A63', fontSize: 11.5, fontWeight: '500', marginTop: 2 },
  previewImage: { backgroundColor: '#ECE8DC', borderColor: '#EDE8DE', borderRadius: 20, borderWidth: 1, height: 104, width: 150 },
  fieldsCard: { backgroundColor: '#FAF8F3', borderColor: '#EDE8DE', borderRadius: 28, borderWidth: 1, marginTop: 16, overflow: 'hidden', shadowColor: '#28372D', shadowOpacity: 0.04, shadowRadius: 10 },
  fieldRow: { alignItems: 'center', flexDirection: 'row', minHeight: 82, paddingHorizontal: 15, paddingVertical: 14 },
  fieldContent: { flex: 1, minWidth: 0 },
  fieldLabel: { color: '#1F2E23', fontSize: 13, fontWeight: '700', marginBottom: 5 },
  fieldValue: { color: '#1F2E23', fontSize: 14 },
  input: { color: '#1F2E23', flex: 1, fontSize: 14, padding: 0 },
  divider: { backgroundColor: '#EDE8DE', height: 1, marginLeft: 82 },
  greenBadge: { alignItems: 'center', backgroundColor: '#E4ECE7', borderRadius: 23, height: 46, justifyContent: 'center', marginRight: 14, width: 46 },
  apricotBadge: { alignItems: 'center', backgroundColor: '#F2E5D5', borderRadius: 23, height: 46, justifyContent: 'center', marginRight: 14, width: 46 },
  coralBadge: { alignItems: 'center', backgroundColor: '#F8DFD7', borderRadius: 23, height: 46, justifyContent: 'center', marginRight: 14, width: 46 },
  badgeGlyph: { color: '#557A63', fontSize: 20 },
  chevron: { color: '#8C9C90', fontSize: 20, marginLeft: 10 },
  optionsPanel: { backgroundColor: '#F4F0E6', borderTopColor: '#EDE8DE', borderTopWidth: 1, flexDirection: 'row', flexWrap: 'wrap', gap: 6, padding: 12 },
  option: { alignItems: 'center', backgroundColor: '#FFFFFFCC', borderRadius: 12, flexDirection: 'row', minWidth: '47%', paddingHorizontal: 12, paddingVertical: 10 },
  selectedOption: { backgroundColor: '#627C6B' },
  optionIcon: { color: '#627C6B', fontSize: 16, marginRight: 8 },
  optionText: { color: '#304135', flexShrink: 1, fontSize: 12, fontWeight: '600' },
  selectedOptionText: { color: '#FFFFFF' },
  breedPanel: { backgroundColor: '#F4F0E6', borderTopColor: '#EDE8DE', borderTopWidth: 1, padding: 12 },
  panelLabel: { color: '#7D8F82', fontSize: 10, fontWeight: '700', letterSpacing: 0.8, marginBottom: 5 },
  breedOption: { alignItems: 'center', backgroundColor: '#FFFFFFCC', borderRadius: 10, flexDirection: 'row', justifyContent: 'space-between', marginTop: 4, paddingHorizontal: 12, paddingVertical: 10 },
  checkmark: { color: '#627C6B', fontSize: 16, fontWeight: '800' },
  unitToggle: { backgroundColor: '#EAE4D7', borderColor: '#DDD6C8', borderRadius: 18, borderWidth: 1, flexDirection: 'row', padding: 2 },
  unitButton: { borderRadius: 14, paddingHorizontal: 9, paddingVertical: 5 },
  activeUnit: { backgroundColor: '#FFFFFF' },
  unitText: { color: '#6C7E72', fontSize: 11, fontWeight: '700' },
  activeUnitText: { color: '#1F2E23' },
  error: { color: '#B9553E', fontSize: 12, fontWeight: '600', marginTop: 8, textAlign: 'center' },
  bottomActions: { alignItems: 'center', paddingTop: 24 },
  saveButton: { alignItems: 'center', backgroundColor: '#627C6B', borderRadius: 25, elevation: 3, height: 52, justifyContent: 'center', shadowColor: '#627C6B', shadowOpacity: 0.28, shadowRadius: 10, width: '100%' },
  saveText: { color: '#FFFFFF', fontSize: 16, fontWeight: '700' },
  cancelButton: { paddingBottom: 6, paddingTop: 12 },
  cancelText: { color: '#65776C', fontSize: 14, fontWeight: '500' },
  homeIndicator: { backgroundColor: '#D0C9BA', borderRadius: 2, height: 4, marginTop: 4, width: 128 },
});
